// <auto-generated />
using System;
using ApexBytez.MediaRecon.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApexBytez.MediaRecon.Migrations
{
    [DbContext(typeof(MediaReconContext))]
    [Migration("20220529125215_AddRunStatisticsEntity")]
    partial class AddRunStatisticsEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ApexBytez.MediaRecon.DB.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ApexBytez.MediaRecon.DB.RunStatistics", b =>
                {
                    b.Property<int>("RunStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountOfDataAnalyzed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountOfDuplicateDataRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<long>("DuplicateFilesFound")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DuplicateFilesRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NumberOfFilesAnalayzed")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunStatisticsId");

                    b.ToTable("RunStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
